[general]
import = [ "~/.config/alacritty/themes/gruvbox-dark-hard.toml" ]

[window]
padding = {x = 5, y = 5}
opacity = 0.9

[font]
normal = { family = "Iosevka", style = "Regular" }
size = 16

[mouse]
hide_when_typing = true
