[colors]
primary = { background = "#ffffff", foreground = "#000000" }
cursor = { text = "#ffffff", cursor = "#000000" }
normal = { black =   "#000000", red   =   "#FF0066", green =   "#00DB96", yellow =  "#f39c11", blue  =   "#0000FF", magenta = "#AC00FF", cyan  =   "#00B7DB", white =   "#dadada" }
bright = { black =   "#999999", red   =   "#FF0066", green =   "#00DB96", yellow =  "#FFCC00", blue  =   "#0000FF", magenta = "#FF00FF", cyan  =   "#00B7DB", white =   "#dadada" }
